// flow-typed signature: 8be0d397cf12c2694cddb38bccfb65bc
// flow-typed version: <<STUB>>/@google-cloud/datastore_v1.4.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/datastore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/datastore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/datastore/src/entity' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/index' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/query' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/request' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/transaction' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/v1/datastore_client' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_datastore' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_entity' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_query' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/v1/doc/google/protobuf/doc_wrappers' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/v1/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/datastore/src/entity.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/entity'>;
}
declare module '@google-cloud/datastore/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/index'>;
}
declare module '@google-cloud/datastore/src/query.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/query'>;
}
declare module '@google-cloud/datastore/src/request.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/request'>;
}
declare module '@google-cloud/datastore/src/transaction.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/transaction'>;
}
declare module '@google-cloud/datastore/src/v1/datastore_client.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/v1/datastore_client'>;
}
declare module '@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_datastore.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_datastore'>;
}
declare module '@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_entity.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_entity'>;
}
declare module '@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_query.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/v1/doc/google/datastore/v1/doc_query'>;
}
declare module '@google-cloud/datastore/src/v1/doc/google/protobuf/doc_wrappers.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/v1/doc/google/protobuf/doc_wrappers'>;
}
declare module '@google-cloud/datastore/src/v1/index.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/v1/index'>;
}
