// flow-typed signature: 3816a26109fbd42596e29f2d336d2a8b
// flow-typed version: <<STUB>>/@google-cloud/storage_v1.6.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/storage/src/acl' {
  declare module.exports: any;
}

declare module '@google-cloud/storage/src/bucket' {
  declare module.exports: any;
}

declare module '@google-cloud/storage/src/channel' {
  declare module.exports: any;
}

declare module '@google-cloud/storage/src/file' {
  declare module.exports: any;
}

declare module '@google-cloud/storage/src/iam' {
  declare module.exports: any;
}

declare module '@google-cloud/storage/src/index' {
  declare module.exports: any;
}

declare module '@google-cloud/storage/src/notification' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/storage/src/acl.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/acl'>;
}
declare module '@google-cloud/storage/src/bucket.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/bucket'>;
}
declare module '@google-cloud/storage/src/channel.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/channel'>;
}
declare module '@google-cloud/storage/src/file.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/file'>;
}
declare module '@google-cloud/storage/src/iam.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/iam'>;
}
declare module '@google-cloud/storage/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/index'>;
}
declare module '@google-cloud/storage/src/notification.js' {
  declare module.exports: $Exports<'@google-cloud/storage/src/notification'>;
}
