// flow-typed signature: 3e39d8c93a85c74b793f281d10e89784
// flow-typed version: <<STUB>>/apache-md5_v1.1.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apache-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apache-md5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apache-md5/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apache-md5/src/index.js' {
  declare module.exports: $Exports<'apache-md5/src/index'>;
}
