// flow-typed signature: 44a338cd9ebec553aabfb243383f3698
// flow-typed version: <<STUB>>/unix-crypt-td-js_v1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unix-crypt-td-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unix-crypt-td-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unix-crypt-td-js/dist/unix-crypt-td.min' {
  declare module.exports: any;
}

declare module 'unix-crypt-td-js/src/unix-crypt-td' {
  declare module.exports: any;
}

declare module 'unix-crypt-td-js/test/unix-crypt-td-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unix-crypt-td-js/dist/unix-crypt-td.min.js' {
  declare module.exports: $Exports<'unix-crypt-td-js/dist/unix-crypt-td.min'>;
}
declare module 'unix-crypt-td-js/src/unix-crypt-td.js' {
  declare module.exports: $Exports<'unix-crypt-td-js/src/unix-crypt-td'>;
}
declare module 'unix-crypt-td-js/test/unix-crypt-td-test.js' {
  declare module.exports: $Exports<'unix-crypt-td-js/test/unix-crypt-td-test'>;
}
